### ISSUE TITLE
`image_url' is missed in ProductImage class

### ISSUE THREAD

**Issue by mrself** [moderntribe/bigcommerce-api-php-v3#11]

**Comment by tatiana-perry** [comment]
Hi, 
The [ProductImage](https://github.com/moderntribe/bigcommerce-api-php-v3/blob/master/src/Model/ProductImage.php) class has the `image_file` listed which is correct. The only time `image_url` should be used is when [creating or updating a product image](https://github.com/moderntribe/bigcommerce-api-php-v3/blob/master/src/Model/ProductImagePost.php). We have submitted a ticket to get the developer documentation updated to reflect the correct schema for product images.
